export const AI_PROMPT_SUGGESTIONS = [
  "A pickup line for a software engineer",
  "Something cheesy for a coffee lover",
  "A romantic line about the stars",
  "A funny line to break the ice",
  "A cute line for someone who loves cats",
  "A pickup line about reading books",
  "Something smooth for a gym crush",
  "A cheesy line about pizza",
  "A line for someone with a beautiful smile",
  "A nerdy pickup line about science",
  "A romantic line for a rainy day",
  "Something funny about being bad at flirting",
  "A line for a musician",
  "A cute compliment about their eyes",
  "A pickup line about traveling the world",
  "Something cheesy for a plant parent",
  "A flirty line about cooking together",
  "A pickup line for a gamer",
  "A romantic line about fate",
  "Something smooth about time stopping",
  "A cheesy line about being lost in their eyes",
  "A nerdy line about math and probabilities",
  "A pickup line for someone who loves movies",
  "A line about stealing my heart",
  "Something funny about falling for them",
  "A cheesy line for a dog lover",
  "A smooth line for a beach day",
  "A pickup line about aliens and outer space",
  "A romantic line about long walks",
  "A funny line about forgetting how to talk",
  "A cheesy line about winning the lottery",
  "A line about them being a work of art",
  "Something smooth for someone who loves music",
  "A nerdy line about chemistry",
  "A pickup line for a foodie",
  "A romantic line about the sunset",
  "A cheesy line about being an angel",
  "A funny line about needing a map",
  "A line for someone who loves photography",
  "A cute line about holding hands",
  "A pickup line about being a thief",
  "Something cheesy about the alphabet",
  "A smooth line about making a wish",
  "A nerdy line about internet connection",
  "A romantic line about soulmates",
  "A funny line about tripping and falling",
  "A pickup line for someone who loves art",
  "A cheesy line about being a magician",
  "A smooth line about stopping the clock",
  "A cute line about being a parking ticket",
  "A nerdy line about keyboard shortcuts",
  "A pickup line about being a dictionary",
  "A romantic line about the moon",
  "A cheesy line about sweet desserts",
  "A funny line about calling heaven",
];
