import { Ionicons } from "@expo/vector-icons";
import Feather from "@expo/vector-icons/Feather";
import { useRouter } from "expo-router";
import { useContext, useState, useEffect } from "react";
import {
  ActivityIndicator,
  Keyboard,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View,
  Share,
  ScrollView,
  Alert,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import DynamicBackground from "../../components/DynamicBackground";
import { BlurView } from "expo-blur";
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withSpring,
  runOnJS,
} from "react-native-reanimated";
import * as Haptics from "expo-haptics";
import AsyncStorage from "@react-native-async-storage/async-storage";

import colors from "../../constants/colors";
import { favoritesContext } from "../../context/AppContext";
import { generateCheesyLine } from "../../services/groq";
import { getRandomOfflineLine } from "../../services/offlineAILines";
import { BannerAdComponent } from "../../services/AdManager";
import { AI_PROMPT_SUGGESTIONS } from "../../constants/aiPrompts";

export default function AIGenerator() {
  const router = useRouter();
  const { setFavorites } = useContext(favoritesContext);

  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [generatedLine, setGeneratedLine] = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);
  const [isSaved, setIsSaved] = useState(false);
  const [suggestions, setSuggestions] = useState([]);
  const [showSuggestions, setShowSuggestions] = useState(false);

  useEffect(() => {
    // Pick 6 random suggestions for the modal
    const shuffled = [...AI_PROMPT_SUGGESTIONS].sort(() => 0.5 - Math.random());
    setSuggestions(shuffled.slice(0, 6));
  }, []);

  const backBtnScale = useSharedValue(1);

  const handleBackPressIn = () => {
    backBtnScale.value = withSpring(0.8);
  };

  const handleBackPressOut = () => {
    backBtnScale.value = withSpring(1, {}, (finished) => {
      if (finished) runOnJS(router.back)();
    });
  };

  const backBtnStyle = useAnimatedStyle(() => ({
    transform: [{ scale: backBtnScale.value }],
  }));

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    Keyboard.dismiss();
    setLoading(true);
    setErrorMsg(null);
    setGeneratedLine(null);
    setIsSaved(false);
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);

    try {
      const line = await generateCheesyLine(prompt);
      setGeneratedLine(line);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (error) {
      if (error.message === "NO_API_KEY") {
        // Fallback to offline template
        const offlineLine = getRandomOfflineLine();
        setGeneratedLine(offlineLine);
        setErrorMsg("API Key missing. Showing offline line. Add key in Settings!");
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      } else {
        setErrorMsg(error.message);
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleSaveToFavorites = async () => {
    if (!generatedLine) return;
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    try {
      const newCard = {
        id: Math.random().toString(36).substr(2, 9),
        text: generatedLine,
      };
      const existingData = await AsyncStorage.getItem("favorites");
      let favorites = existingData ? JSON.parse(existingData) : [];
      const isDuplicate = favorites.some((fav) => fav.text === newCard.text);

      if (!isDuplicate) {
        favorites.push(newCard);
        await AsyncStorage.setItem("favorites", JSON.stringify(favorites));
        setFavorites(favorites);
      }
      setIsSaved(true);
    } catch (err) {}
  };

  const handleShareAI = async () => {
    if (!generatedLine) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    try {
      await Share.share({
        message: `${generatedLine}\n\nGenerated by AI ✨ Get more Cheesy Lines: https://destyastudio.com/products/cheezylines`,
      });
    } catch (error) {}
  };

  return (
    <View style={{ flex: 1 }}>
    <DynamicBackground>
      <SafeAreaView style={styles.safeArea}>
      {/* Header */}
      <View style={styles.headerContainer}>
        <Pressable onPressIn={handleBackPressIn} onPressOut={handleBackPressOut} hitSlop={10}>
          <Animated.View style={backBtnStyle}>
            <Ionicons name="arrow-back-sharp" size={36} color="#FFF" />
          </Animated.View>
        </Pressable>
        <Text style={styles.headerText}>AI Magic ✨</Text>
      </View>

      <KeyboardAvoidingView
        style={{ flex: 1, width: "100%", marginBottom: 60 }} // Give space for banner
        behavior={Platform.OS === "ios" ? "padding" : "height"}
      >
        <ScrollView 
          style={styles.content} 
          contentContainerStyle={{ paddingBottom: 40 }}
          keyboardShouldPersistTaps="handled"
        >
          {/* Description */}
            <Text style={styles.description}>
              Describe a scenario, person, or object, and the AI will generate a custom cheesy line just for you!
            </Text>

            {/* Input Area */}
            <View style={styles.inputContainer}>
              <TextInput
                style={styles.input}
                placeholder="e.g. A pickup line about coffee..."
                placeholderTextColor="#999"
                value={prompt}
                onChangeText={setPrompt}
                multiline
                maxLength={150}
              />
              <TouchableOpacity
                style={[styles.generateButton, !prompt.trim() && { opacity: 0.5 }]}
                onPress={handleGenerate}
                disabled={!prompt.trim() || loading}
              >
                {loading ? (
                  <ActivityIndicator color="#FFF" />
                ) : (
                  <Feather name="zap" size={24} color="#FFF" />
                )}
              </TouchableOpacity>
            </View>

            <Text style={styles.warningText}>
              <Feather name="alert-triangle" size={10} color="#999" /> AI can make mistakes. Be careful !
            </Text>

            {/* Suggestion Button */}
            <TouchableOpacity 
              style={styles.suggestionTriggerButton}
              onPress={() => setShowSuggestions(true)}
            >
              <Text style={styles.suggestionTriggerText}>{"Don't know what to type? 🤔"}</Text>
            </TouchableOpacity>

            {/* Error Message */}
            {errorMsg && <Text style={styles.errorText}>{errorMsg}</Text>}

            {/* Result Card */}
            {generatedLine && (
              <View style={styles.gradientBorderContainer}>
                <BlurView intensity={60} tint="dark" style={styles.resultCard}>
                  <TouchableOpacity 
                    style={{ position: 'absolute', top: 15, right: 15, padding: 5, zIndex: 10 }} 
                    onPress={() => {
                      Alert.alert("Report AI Content", "Thanks for letting us know! We'll review this AI generation.");
                    }}
                    hitSlop={15}
                  >
                    <Feather name="flag" size={16} color="#B0BEC5" />
                  </TouchableOpacity>

                  <Text style={styles.resultText}>{generatedLine}</Text>
                  
                  <View style={{ flexDirection: "row", gap: 15 }}>
                    <TouchableOpacity 
                      style={[styles.saveButton, isSaved && { backgroundColor: "#E8F5E9" }]} 
                      onPress={handleSaveToFavorites}
                      disabled={isSaved}
                    >
                      <Feather name={isSaved ? "check" : "heart"} size={20} color={isSaved ? "#4CAF50" : colors.BRAND_ORANGE} />
                      <Text style={[styles.saveButtonText, isSaved && { color: "#4CAF50" }]}>
                        {isSaved ? "Saved!" : "Save"}
                      </Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={styles.shareButton} onPress={handleShareAI}>
                      <Feather name="share-2" size={20} color={colors.BRAND_ORANGE} />
                      <Text style={styles.shareButtonText}>Share</Text>
                    </TouchableOpacity>
                  </View>
                </BlurView>
              </View>
            )}
        </ScrollView>
      </KeyboardAvoidingView>

      <View style={styles.bannerContainer}>
        <BannerAdComponent />
      </View>

      {/* In-page suggestions overlay — stays within phone frame on web */}
      {showSuggestions && (
        <View style={styles.overlayBackdrop}>
          <View style={styles.overlaySheet}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Need Inspiration? 💡</Text>
              <TouchableOpacity onPress={() => setShowSuggestions(false)}>
                <Feather name="x" size={24} color="#333" />
              </TouchableOpacity>
            </View>
            <ScrollView contentContainerStyle={styles.suggestionsContainer} showsVerticalScrollIndicator={false}>
              {suggestions.map((s, index) => (
                <TouchableOpacity
                  key={index}
                  style={styles.suggestionChip}
                  onPress={() => {
                    setPrompt(s);
                    Haptics.selectionAsync();
                    setShowSuggestions(false);
                  }}
                >
                  <Text style={styles.suggestionText}>{s}</Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
        </View>
      )}
    </SafeAreaView>
    </DynamicBackground>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    alignItems: "center",
  },
  headerContainer: {
    paddingVertical: 10,
    display: "flex",
    flexDirection: "row",
    gap: 15,
    width: "90%",
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    zIndex: 10,
  },
  headerText: {
    color: "#FFF",
    fontSize: 26,
    fontFamily: "Outfit-Bold",
  },
  content: {
    flex: 1,
    width: "90%",
    alignSelf: "center",
    paddingTop: 30,
  },
  bannerContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  description: {
    fontFamily: "Outfit-Regular",
    fontSize: 16,
    color: "rgba(255,255,255,0.7)",
    marginBottom: 25,
    textAlign: "center",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },

  suggestionChip: {
    backgroundColor: "#E1F5FE",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#B3E5FC",
    width: "100%",
  },
  suggestionText: {
    fontFamily: "Poppins-Regular",
    fontSize: 14,
    color: "#0277BD",
    textAlign: "center",
  },
  warningText: {
    fontFamily: "Poppins-Regular",
    fontSize: 10,
    color: "#999",
    textAlign: "center",
    marginBottom: 20,
  },
  suggestionsContainer: {
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
  },
  suggestionTriggerButton: {
    alignSelf: "center",
    backgroundColor: "#F0F0F0",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginBottom: 20,
  },
  suggestionTriggerText: {
    fontFamily: "Poppins-Regular",
    fontSize: 14,
    color: "#555",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    padding: 25,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: "Poppins-Bold",
    fontSize: 18,
    color: "#333",
  },
  input: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 24,
    padding: 15,
    paddingTop: 15,
    minHeight: 60,
    maxHeight: 120,
    fontFamily: "Outfit-Regular",
    fontSize: 16,
    color: "#FFF",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  generateButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.BRAND_ORANGE,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.BRAND_ORANGE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  errorText: {
    fontFamily: "Poppins-Regular",
    color: "#E53935",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 20,
  },
  gradientBorderContainer: {
    marginTop: 20,
    shadowColor: colors.BRAND_ORANGE,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  resultCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    padding: 25,
    alignItems: "center",
    overflow: "hidden",
  },
  resultText: {
    fontFamily: "Playfair-BoldItalic",
    fontSize: 26,
    color: "#FFF",
    textAlign: "center",
    lineHeight: 36,
    marginBottom: 30,
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    gap: 8,
  },
  saveButtonText: {
    fontFamily: "Outfit-Bold",
    color: colors.BRAND_ORANGE,
    fontSize: 16,
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    gap: 8,
  },
  shareButtonText: {
    fontFamily: "Outfit-Bold",
    color: colors.BRAND_ORANGE,
    fontSize: 16,
  },
  // In-page overlay (replaces Modal so it stays within phone frame on web)
  overlayBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
    zIndex: 100,
  },
  overlaySheet: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    padding: 25,
    maxHeight: "75%",
  },
});
